# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Build

on:
  push:
    branches: [psycho]
  pull_request:
    branches: [psycho]

jobs:
  build:
    strategy:
      matrix:
        java: [11]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.java }}, OS ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Build with Maven
        run: mvn -V -B install
